# Generated by Django 3.2.3 on 2022-10-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parahareketimodel',
            name='odeme_turu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='antrenormodel',
            name='adi',
            field=models.CharField(max_length=250, verbose_name='Ad Soyad'),
        ),
    ]
