# Generated by Django 3.2.3 on 2022-08-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='aktif_mi',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi'),
        ),
    ]
