# Generated by Django 3.2.13 on 2022-07-31 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uyegrupmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Üye Grubu', 'verbose_name_plural': 'Üye Gruplar'},
        ),
        migrations.AddField(
            model_name='grupmodel',
            name='adi',
            field=models.CharField(max_length=250, null=True, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='grup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etkinlik_grup_relations', to='calendarapp.grupmodel', verbose_name='Katılımcı Grubu'),
        ),
    ]
