# Generated by Django 3.2.3 on 2022-10-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20221013_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telafidersmodel',
            name='kullanilan_etkinlik',
        ),
        migrations.AddField(
            model_name='telafidersmodel',
            name='yapilan_antrenor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telafi_ders_antrenor', to='calendarapp.antrenormodel'),
        ),
        migrations.AddField(
            model_name='telafidersmodel',
            name='yapilan_kort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telafi_ders_kort', to='calendarapp.kortmodel'),
        ),
        migrations.AddField(
            model_name='telafidersmodel',
            name='yapilma_aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Etkinlik Açıklaması'),
        ),
        migrations.AddField(
            model_name='telafidersmodel',
            name='yapilma_tarih_saat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etkinlik Tarihi'),
        ),
    ]
