# Generated by Django 3.2.3 on 2022-08-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_rezervasyonmodel_aktif_mi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervasyonmodel',
            name='adi',
        ),
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='uye',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rezervasyonlar', to='calendarapp.uyemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etkinlikkatilimmodel',
            name='uye',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uye', to='calendarapp.uyemodel', verbose_name='Üye'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='grup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etkinlik_grup_relations', to='calendarapp.grupmodel', verbose_name='Katılımcı Grubu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='kort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kort', to='calendarapp.kortmodel', verbose_name='Kort'),
            preserve_default=False,
        ),
    ]
