# Generated by Django 3.2.13 on 2022-06-08 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0002_alter_rezervasyonmodel_baslik'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='renk',
            field=models.CharField(blank=True, choices=[('Kırmızı', 'red'), ('Mavi', 'blue')], max_length=20, null=True, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='aciklama',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='baslangic_tarih_saat',
            field=models.DateTimeField(verbose_name='Başlangıç Tarih Saat'),
        ),
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='bitis_tarih_saat',
            field=models.DateTimeField(verbose_name='Bitiş Tarih Saat'),
        ),
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
    ]
