# Generated by Django 3.2.13 on 2022-07-28 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0002_auto_20220727_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtkinlikKatilimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etkinlik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etkinlik', to='calendarapp.etkinlikmodel', verbose_name='Etkinlik')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etkinlik_katilim', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('uye', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uye', to='calendarapp.uyemodel', verbose_name='Üye')),
            ],
            options={
                'verbose_name': 'Etkinlik Katılım',
                'verbose_name_plural': 'Etkinlik Katılımları',
                'ordering': ['-id'],
            },
        ),
    ]
