# Generated by Django 3.2.13 on 2022-07-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20220731_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupmodel',
            name='tekil_mi',
            field=models.BooleanField(default=False, verbose_name='Tekil Mi'),
        ),
    ]
