# Generated by Django 3.2.3 on 2022-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20221018_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrenormodel',
            name='renk',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Mavi'), ('yellow', 'Sarı'), ('green', 'Yeşil')], default='purple', max_length=20, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='seviye_rengi',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('orange', 'Turuncu'), ('green', 'Yeşil'), ('yellow', 'Sarı')], default='red', max_length=20, verbose_name='Seviye Rengi'),
        ),
    ]
