# Generated by Django 3.2.13 on 2022-07-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_etkinlikkatilimmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlikmodel',
            name='tamamlandi_mi',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı mı?'),
        ),
    ]
