# Generated by Django 3.2.13 on 2022-08-16 23:57

import calendarapp.models.concrete.uye
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20220812_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyemodel',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='uyemodel',
            name='onaylandi_mi',
            field=models.BooleanField(default=False, verbose_name='Onaylandı mı'),
        ),
        migrations.AddField(
            model_name='uyemodel',
            name='uye_no',
            field=models.IntegerField(default=calendarapp.models.concrete.uye.uye_no_uret, verbose_name='Üye No'),
        ),
    ]
