# Generated by Django 3.2.13 on 2022-07-31 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_grupmodel_tekil_mi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telafidersmodel',
            name='kullanilan_etkinlik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kullanilanDers', to='calendarapp.etkinlikmodel', verbose_name='Kullanılan Etkinlik'),
        ),
    ]
