# Generated by Django 3.2.13 on 2022-08-17 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20220816_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='antrenor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antrenor', to='calendarapp.antrenormodel'),
        ),
    ]
