# Generated by Django 3.2.13 on 2022-08-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_telafidersmodel_kullanilan_etkinlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telafidersmodel',
            name='kullanilan_etkinlik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kullanilanDers', to='calendarapp.etkinlikmodel', verbose_name='Kullanılan Etkinlik'),
        ),
    ]
