# Generated by Django 3.2.13 on 2022-07-29 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0004_etkinlikmodel_tamamlandi_mi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelafiDersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('kullanilan_etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanilanDers', to='calendarapp.etkinlikmodel', verbose_name='Kullanılan Etkinlik')),
                ('telafi_etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telafiDers', to='calendarapp.etkinlikmodel', verbose_name='Etkinlik')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telafiDers', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telafiDers', to='calendarapp.uyemodel', verbose_name='Üye')),
            ],
            options={
                'verbose_name': 'Antrenor',
                'verbose_name_plural': 'Antrenor',
                'ordering': ['id'],
            },
        ),
    ]
