# Generated by Django 3.2.13 on 2022-06-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_rezervasyonmodel_renk'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='tekrar',
            field=models.IntegerField(default=0, verbose_name='Tekrar Sayısı'),
        ),
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='renk',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Mavi'), ('yellow', 'Sarı'), ('green', 'Yeşil')], default='gray', max_length=20, verbose_name='Renk'),
        ),
    ]
