# Generated by Django 3.2.13 on 2022-09-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_rezervasyonmodel_antrenor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyegrupmodel',
            name='odeme_sekli',
            field=models.CharField(blank=True, choices=[(1, 'Ortak_Odeme'), (2, 'Bireysel_Odeme')], max_length=100, null=True, verbose_name='Ödeme Şekli'),
        ),
    ]
