# Generated by Django 3.2.3 on 2022-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_paketkullanimmodel_kalan_adet'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlikmodel',
            name='tamamlandi_onay',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı mı? (Yönetici)'),
        ),
    ]
