# Generated by Django 3.2.13 on 2022-06-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20220608_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='tekrar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tekrar Sayısı'),
        ),
    ]
