# Generated by Django 3.2.13 on 2022-09-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_alter_uyegrupmodel_odeme_sekli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyegrupmodel',
            name='odeme_sekli',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Ortak_Odeme'), (2, 'Bireysel_Odeme')], null=True, verbose_name='Ödeme Şekli'),
        ),
    ]
