# Generated by Django 3.2.13 on 2022-06-10 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0006_alter_rezervasyonmodel_tekrar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtkinlikMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RezervasyonModel',
            new_name='EtkinlikModel',
        ),
        migrations.DeleteModel(
            name='RezervasyonMember',
        ),
        migrations.AddField(
            model_name='etkinlikmember',
            name='etkinlik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etkinlik', to='calendarapp.etkinlikmodel'),
        ),
        migrations.AddField(
            model_name='etkinlikmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='etkinlikmember',
            unique_together={('etkinlik', 'user')},
        ),
    ]
