# Generated by Django 3.2.3 on 2022-10-27 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_etkinlikmodel_tamamlandi_onay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikkatilimmodel',
            name='etkinlik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etkinlik_etkinlikkatilim_relations', to='calendarapp.etkinlikmodel', verbose_name='Etkinlik'),
        ),
    ]
