# Generated by Django 3.2.13 on 2022-09-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_alter_uyegrupmodel_odeme_sekli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etkinlikmodel',
            name='renk',
        ),
        migrations.AddField(
            model_name='antrenormodel',
            name='renk',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Mavi'), ('yellow', 'Sarı'), ('green', 'Yeşil')], default='gray', max_length=20, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='grupmodel',
            name='adi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adı'),
        ),
    ]
