# Generated by Django 3.2.13 on 2022-06-14 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0008_auto_20220614_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etkinlikmodel',
            name='uye',
        ),
        migrations.RenameModel(
            old_name='MusteriModel',
            new_name='UyeModel',
        ),
        migrations.CreateModel(
            name='UyeGrupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uye1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uye1', to='calendarapp.uyemodel')),
                ('uye2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uye2', to='calendarapp.uyemodel')),
                ('uye3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uye3', to='calendarapp.uyemodel')),
                ('uye4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uye4', to='calendarapp.uyemodel')),
            ],
            options={
                'verbose_name': 'Üye Grubu',
                'verbose_name_plural': 'Gruplar',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='etkinlikmodel',
            name='grup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grup', to='calendarapp.uyegrupmodel', verbose_name='Katılımcı Grubu'),
        ),
    ]
