# Generated by Django 3.2.3 on 2022-11-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_rename_abonelikmodel_uyeabonelikmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyemodel',
            name='seviye_rengi',
            field=models.CharField(choices=[('Kırmızı', 'red'), ('Turuncu', 'orange'), ('Yeşil', 'green'), ('Sarı', 'yellow')], default='red', max_length=20, verbose_name='Seviye Rengi'),
        ),
    ]
