# Generated by Django 3.2.13 on 2022-09-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_auto_20220904_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyemodel',
            name='seviye_rengi',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Mavi'), ('green', 'Yeşil')], default='gray', max_length=20, verbose_name='Renk'),
        ),
    ]
