# Generated by Django 3.2.3 on 2022-11-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_alter_uyemodel_seviye_rengi'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketmodel',
            name='ozellikler',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Özellikler'),
        ),
    ]
