# Generated by Django 3.2.13 on 2022-09-04 23:50

import calendarapp.models.Enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0009_uyemodel_seviye_rengi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonelikModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('aktif_mi', models.BooleanField(default=True)),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Abonelik',
                'verbose_name_plural': 'Abonelik',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adi', models.CharField(max_length=200, verbose_name='Paket Adı')),
                ('tipi', models.SmallIntegerField(choices=[(1, 'Paket'), (2, 'Uyelik')], default=calendarapp.models.Enums.AbonelikTipikEnum['Uyelik'], verbose_name='Tipi')),
                ('adet', models.IntegerField(blank=True, null=True, verbose_name='Adet')),
                ('toplam_fiyati', models.IntegerField(blank=True, null=True, verbose_name='Toplam Fiyatı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paket', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaketKullanimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abonelik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.abonelikmodel', verbose_name='Abonelik')),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.etkinlikmodel', verbose_name='Etkinlik')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paket_kullanim', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.uyemodel', verbose_name='Üye')),
            ],
            options={
                'verbose_name': 'Paket Kullanım',
                'verbose_name_plural': 'Paket Kullanım',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='abonelikmodel',
            name='paket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendarapp.paketmodel', verbose_name='Paket'),
        ),
        migrations.AddField(
            model_name='abonelikmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonelik', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.AddField(
            model_name='abonelikmodel',
            name='uye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.uyemodel', verbose_name='Üye'),
        ),
    ]
