# Generated by Django 3.2.3 on 2022-11-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_paketmodel_ozellikler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketmodel',
            name='adi',
            field=models.CharField(max_length=200, verbose_name='Paket / Abonelik Adı'),
        ),
        migrations.AlterField(
            model_name='paketmodel',
            name='ozellikler',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Özellikler'),
        ),
    ]
