# Generated by Django 3.2.13 on 2022-07-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0012_kortmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlikmodel',
            name='kort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kort', to='calendarapp.kortmodel', verbose_name='Kort'),
        ),
    ]
