# Generated by Django 3.2.13 on 2022-12-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0012_auto_20221121_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etkinlikmodel',
            old_name='tamamlandi_mi',
            new_name='tamamlandi_antrenor',
        ),
        migrations.RenameField(
            model_name='etkinlikmodel',
            old_name='tamamlandi_onay',
            new_name='tamamlandi_yonetici',
        ),
        migrations.RemoveField(
            model_name='etkinlikmodel',
            name='baslik',
        ),
        migrations.RemoveField(
            model_name='etkinlikmodel',
            name='tekrar',
        ),
        migrations.AddField(
            model_name='etkinlikmodel',
            name='abonelik_tipi',
            field=models.CharField(choices=[(1, 'Paket'), (2, 'Aidat')], default=2, max_length=20, verbose_name='Abonelik Tipi'),
        ),
        migrations.AddField(
            model_name='etkinlikmodel',
            name='tamamlandi_uye',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı mı? (Üye)'),
        ),
    ]
