# Generated by Django 3.2.13 on 2022-07-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0013_etkinlikmodel_kort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kortmodel',
            options={'ordering': ['id'], 'verbose_name': 'Kort', 'verbose_name_plural': 'Kort'},
        ),
    ]
