# Generated by Django 3.2.13 on 2022-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0013_auto_20221201_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='abonelik_tipi',
            field=models.IntegerField(choices=[(1, 'Paket'), (2, 'Aidat')], default=2, max_length=20, verbose_name='Abonelik Tipi'),
        ),
    ]
