# Generated by Django 3.2.13 on 2022-12-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0014_alter_etkinlikmodel_abonelik_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlikmodel',
            name='top_rengi',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Mavi'), ('yellow', 'Sarı'), ('green', 'Yeşil')], default='purple', max_length=20, verbose_name='Renk'),
        ),
    ]
