# Generated by Django 3.2.13 on 2022-12-01 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0015_etkinlikmodel_top_rengi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uyeabonelikmodel',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='uyeabonelikmodel',
            name='baslangic_tarihi',
        ),
        migrations.RemoveField(
            model_name='uyeabonelikmodel',
            name='bitis_tarihi',
        ),
        migrations.RemoveField(
            model_name='uyeabonelikmodel',
            name='paket',
        ),
        migrations.AddField(
            model_name='uyeabonelikmodel',
            name='baslangic_tarih_saat',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uyeabonelikmodel',
            name='bitis_tarih_saat',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bitiş Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uyeabonelikmodel',
            name='gun_adi',
            field=models.CharField(default='Pazartesi', max_length=20, verbose_name='Gün Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uyeabonelikmodel',
            name='haftanin_gunu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gün'),
        ),
        migrations.AddField(
            model_name='uyeabonelikmodel',
            name='kort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.kortmodel', verbose_name='Kort'),
            preserve_default=False,
        ),
    ]
