# Generated by Django 3.2.13 on 2022-12-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0016_auto_20221201_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyeabonelikmodel',
            name='grup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.grupmodel', verbose_name='Katılımcı Grubu'),
            preserve_default=False,
        ),
    ]
