# Generated by Django 3.2.13 on 2022-12-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0017_uyeabonelikmodel_grup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UyePaketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('haftanin_gunu', models.IntegerField(blank=True, null=True, verbose_name='Gün')),
                ('gun_adi', models.CharField(max_length=20, verbose_name='Gün Adı')),
                ('baslangic_tarih_saat', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarih_saat', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('aktif_mi', models.BooleanField(default=True)),
                ('kort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.kortmodel', verbose_name='Kort')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_uyepaket_relations', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.uyemodel', verbose_name='Üye')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
