# Generated by Django 3.2.13 on 2022-07-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0017_rezervasyongunler_rezervasyonmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunlerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=250)),
                ('haftanini_gunu', models.IntegerField()),
                ('hafta_ici_mi', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Günler',
                'verbose_name_plural': 'Günler',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaatlerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=250)),
                ('baslangic_degeri', models.TimeField()),
                ('bitis_degeri', models.TimeField()),
            ],
            options={
                'verbose_name': 'Saatler',
                'verbose_name_plural': 'Saatler',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='rezervasyonmodel',
            name='saat_baslangic',
        ),
        migrations.RemoveField(
            model_name='rezervasyonmodel',
            name='saat_bitis',
        ),
        migrations.DeleteModel(
            name='RezervasyonGunler',
        ),
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='gunler',
            field=models.ManyToManyField(blank=True, null=True, to='calendarapp.GunlerModel', verbose_name='Günler'),
        ),
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='saatler',
            field=models.ManyToManyField(blank=True, null=True, to='calendarapp.SaatlerModel', verbose_name='Saatler'),
        ),
    ]
