# Generated by Django 3.2.13 on 2022-07-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0018_auto_20220726_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gunlermodel',
            name='haftanini_gunu',
        ),
        migrations.AddField(
            model_name='gunlermodel',
            name='haftanin_gunu',
            field=models.IntegerField(default=0, verbose_name='Haftanın Kaçıncı Günü'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gunlermodel',
            name='hafta_ici_mi',
            field=models.BooleanField(default=False, verbose_name='Hafta için mi'),
        ),
    ]
