# Generated by Django 3.2.13 on 2022-12-02 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0018_uyepaketmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uyepaketmodel',
            options={'ordering': ['id'], 'verbose_name': 'Üyenin Paketleri', 'verbose_name_plural': 'Üyenin Paketleri'},
        ),
        migrations.RemoveField(
            model_name='paketkullanimmodel',
            name='abonelik',
        ),
        migrations.RemoveField(
            model_name='paketkullanimmodel',
            name='kalan_adet',
        ),
        migrations.RemoveField(
            model_name='parahareketimodel',
            name='paket',
        ),
        migrations.RemoveField(
            model_name='uyepaketmodel',
            name='gun_adi',
        ),
        migrations.RemoveField(
            model_name='uyepaketmodel',
            name='haftanin_gunu',
        ),
        migrations.AddField(
            model_name='paketkullanimmodel',
            name='uye_paket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.uyepaketmodel', verbose_name='Paket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uyepaketmodel',
            name='adet',
            field=models.IntegerField(default=0, verbose_name='Adet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uyepaketmodel',
            name='ozellikler',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Özellikler'),
        ),
        migrations.AddField(
            model_name='uyepaketmodel',
            name='toplam_fiyati',
            field=models.IntegerField(blank=True, null=True, verbose_name='Toplam Fiyatı'),
        ),
        migrations.AlterField(
            model_name='uyepaketmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uyepaket_relations', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.DeleteModel(
            name='PaketModel',
        ),
    ]
