# Generated by Django 3.2.13 on 2022-07-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0019_auto_20220726_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='onem_derecesi',
            field=models.IntegerField(default=0, verbose_name='Önem Derecesi'),
        ),
    ]
