# Generated by Django 3.2.13 on 2022-12-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0019_auto_20221202_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='abonelik_tipi',
            field=models.IntegerField(choices=[(1, 'Paket'), (2, 'Aidat')], default=2, verbose_name='Abonelik Tipi'),
        ),
        migrations.AlterField(
            model_name='uyepaketmodel',
            name='baslangic_tarih_saat',
            field=models.DateField(verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='uyepaketmodel',
            name='bitis_tarih_saat',
            field=models.DateField(verbose_name='Bitiş Tarihi'),
        ),
    ]
