# Generated by Django 3.2.13 on 2022-07-26 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0020_auto_20220726_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etkinlik', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rezervasyon', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
    ]
