# Generated by Django 3.2.13 on 2022-07-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0021_auto_20220726_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='gunler',
            field=models.ManyToManyField(blank=True, null=True, related_name='gunler_rezervasyon_tablosu', to='calendarapp.GunlerModel', verbose_name='Günler'),
        ),
        migrations.AlterField(
            model_name='rezervasyonmodel',
            name='saatler',
            field=models.ManyToManyField(blank=True, null=True, related_name='saatler_rezervasyon_tablosu', to='calendarapp.SaatlerModel', verbose_name='Saatler'),
        ),
    ]
