# Generated by Django 3.2.3 on 2022-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0021_alter_etkinlikmodel_top_rengi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kortmodel',
            name='max_etkinlik_sayisi',
            field=models.IntegerField(default=4, verbose_name='Maksimum Etkinlik Sayısı'),
        ),
    ]
