# Generated by Django 3.2.3 on 2022-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0022_kortmodel_max_etkinlik_sayisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uyepaketmodel',
            old_name='baslangic_tarih_saat',
            new_name='baslangic_tarih',
        ),
        migrations.RemoveField(
            model_name='uyepaketmodel',
            name='bitis_tarih_saat',
        ),
        migrations.AddField(
            model_name='uyepaketmodel',
            name='bitis_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='uyepaketmodel',
            name='toplam_fiyati',
            field=models.IntegerField(default=0, verbose_name='Toplam Fiyatı'),
            preserve_default=False,
        ),
    ]
