# Generated by Django 3.2.13 on 2022-12-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0023_auto_20221207_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uyepaketmodel',
            name='kort',
        ),
        migrations.AddField(
            model_name='uyepaketmodel',
            name='grup_mu',
            field=models.BooleanField(default=False, verbose_name='Grup Paketi Mi?'),
        ),
        migrations.AlterField(
            model_name='antrenormodel',
            name='renk',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Turuncu'), ('yellow', 'Sarı'), ('green', 'Yeşil')], default='gray', max_length=20, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='top_rengi',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Turuncu'), ('yellow', 'Sarı'), ('green', 'Yeşil')], default='gray', max_length=20, verbose_name='Top Rengi'),
        ),
        migrations.DeleteModel(
            name='EtkinlikKatilimModel',
        ),
    ]
