# Generated by Django 3.2.13 on 2022-12-12 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0024_auto_20221211_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrenormodel',
            name='renk',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('orange', 'Turuncu'), ('yellow', 'Sarı'), ('green', 'Yeşil')], default='gray', max_length=20, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='top_rengi',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('orange', 'Turuncu'), ('yellow', 'Sarı'), ('green', 'Yeşil')], default='gray', max_length=20, verbose_name='Top Rengi'),
        ),
        migrations.CreateModel(
            name='HaftalikPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yil', models.IntegerField(verbose_name='Yıl')),
                ('hafta', models.IntegerField(verbose_name='Hafta')),
                ('abonelik_tipi', models.IntegerField(choices=[(1, 'Paket'), (2, 'Üyelik')], default=2, verbose_name='Abonelik Tipi')),
                ('baslangic_tarih_saat', models.DateTimeField(verbose_name='Başlangıç Tarih Saat')),
                ('bitis_tarih_saat', models.DateTimeField(verbose_name='Bitiş Tarih Saat')),
                ('top_rengi', models.CharField(choices=[('red', 'Kırmızı'), ('orange', 'Turuncu'), ('yellow', 'Sarı'), ('green', 'Yeşil')], default='gray', max_length=20, verbose_name='Top Rengi')),
                ('aciklama', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('antrenor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haftalikplan_antrenor_relations', to='calendarapp.antrenormodel', verbose_name='Antrenör')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haftalikplan_grup_relations', to='calendarapp.grupmodel', verbose_name='Katılımcı Grubu')),
                ('kort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haftalikplan_kort_relations', to='calendarapp.kortmodel', verbose_name='Kort')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haftalikplan_user_relations', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
            ],
            options={
                'verbose_name': 'Haftalik Plan',
                'verbose_name_plural': 'Haftalik Planlar',
                'ordering': ['-id'],
            },
        ),
    ]
