# Generated by Django 3.2.13 on 2022-12-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0026_auto_20221212_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haftalikplanmodel',
            name='baslangic_tarih_saat',
        ),
        migrations.RemoveField(
            model_name='haftalikplanmodel',
            name='bitis_tarih_saat',
        ),
    ]
