# Generated by Django 3.2.13 on 2022-12-12 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0028_auto_20221212_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uyeabonelikmodel',
            name='baslangic_saat',
        ),
        migrations.RemoveField(
            model_name='uyeabonelikmodel',
            name='bitis_saat',
        ),
        migrations.AddField(
            model_name='uyeabonelikmodel',
            name='baslangic_tarih_saat',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uyeabonelikmodel',
            name='bitis_tarih_saat',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bitiş Tarihi'),
            preserve_default=False,
        ),
    ]
