# Generated by Django 3.2.3 on 2022-12-13 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0029_auto_20221212_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlikmodel',
            name='plan_kodu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='haftalikplanmodel',
            name='kod',
            field=models.CharField(default=uuid.UUID('fe99c9a8-7af6-11ed-a6cb-a4bb6d5da4ae'), max_length=50, verbose_name='Plan Kodu'),
        ),
    ]
