# Generated by Django 3.2.3 on 2022-12-15 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0030_auto_20221213_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etkinlikmodel',
            old_name='plan_kodu',
            new_name='haftalik_plan_kodu',
        ),
        migrations.AlterField(
            model_name='haftalikplanmodel',
            name='kod',
            field=models.CharField(default=uuid.UUID('68924fe9-7c79-11ed-afd2-a4bb6d5da4ae'), max_length=50, verbose_name='Plan Kodu'),
        ),
    ]
