# Generated by Django 3.2.3 on 2022-12-15 17:07

import calendarapp.models.concrete.etkinlik
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0031_auto_20221215_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haftalikplanmodel',
            name='kod',
            field=models.UUIDField(default=calendarapp.models.concrete.etkinlik.generate_uuid, editable=False, verbose_name='Plan Kodu'),
        ),
    ]
