# Generated by Django 3.2.3 on 2022-12-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0032_alter_haftalikplanmodel_kod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etkinlikmodel',
            name='ilk_etkinlik_id',
        ),
    ]
