# Generated by Django 3.2.13 on 2023-01-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0033_remove_etkinlikmodel_ilk_etkinlik_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrenormodel',
            name='renk',
            field=models.CharField(choices=[('Kirmizi', 'Kırmızı'), ('Turuncu', 'Turuncu'), ('Sari', 'Sarı'), ('Yesil', 'Yeşil'), ('Yetiskin', 'Yetişkin'), ('TenisOkulu', 'Tenis Okulu')], default='gray', max_length=20, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='top_rengi',
            field=models.CharField(choices=[('Kirmizi', 'Kırmızı'), ('Turuncu', 'Turuncu'), ('Sari', 'Sarı'), ('Yesil', 'Yeşil'), ('Yetiskin', 'Yetişkin'), ('TenisOkulu', 'Tenis Okulu')], default='gray', max_length=20, verbose_name='Top Rengi'),
        ),
        migrations.AlterField(
            model_name='haftalikplanmodel',
            name='top_rengi',
            field=models.CharField(choices=[('Kirmizi', 'Kırmızı'), ('Turuncu', 'Turuncu'), ('Sari', 'Sarı'), ('Yesil', 'Yeşil'), ('Yetiskin', 'Yetişkin'), ('TenisOkulu', 'Tenis Okulu')], default='gray', max_length=20, verbose_name='Top Rengi'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='seviye_rengi',
            field=models.CharField(choices=[('Kirmizi', 'Kırmızı'), ('Turuncu', 'Turuncu'), ('Sari', 'Sarı'), ('Yesil', 'Yeşil'), ('Yetiskin', 'Yetişkin'), ('TenisOkulu', 'Tenis Okulu')], default='red', max_length=20, verbose_name='Seviye Rengi'),
        ),
    ]
