# Generated by Django 3.2.3 on 2023-01-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0034_auto_20230118_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='top_rengi',
            field=models.CharField(choices=[('Kirmizi', 'Kırmızı'), ('Turuncu', 'Turuncu'), ('Sari', 'Sarı'), ('Yesil', 'Yeşil'), ('Yetiskin', 'Yetişkin'), ('TenisOkulu', 'Tenis Okulu')], default='Kirmizi', max_length=20, verbose_name='Top Rengi'),
        ),
    ]
