# Generated by Django 3.2.3 on 2023-01-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0035_alter_etkinlikmodel_top_rengi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='abonelik_tipi',
            field=models.IntegerField(choices=[], default=2, verbose_name='Ders Tipi'),
        ),
        migrations.AlterField(
            model_name='haftalikplanmodel',
            name='abonelik_tipi',
            field=models.IntegerField(choices=[('Paket', 'Paket'), ('Aidat', 'Aidat'), ('Telafi', 'Telafi'), ('Demo', 'Demo'), ('Tek Ders', 'TekDers'), ('Diğer', 'Diger')], default=2, verbose_name='Abonelik Tipi'),
        ),
    ]
