# Generated by Django 3.2.13 on 2023-02-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0039_auto_20230123_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='haftalikplanmodel',
            name='ders_baslangic_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Ders Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='rezervasyonmodel',
            name='referans',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referans'),
        ),
    ]
