# Generated by Django 3.2.13 on 2023-02-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0040_auto_20230202_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyemodel',
            name='uye_tipi',
            field=models.SmallIntegerField(choices=[('Yetişkin', 1), ('Genç', 2)], default=1, verbose_name='Üye Tipi'),
        ),
        migrations.AddField(
            model_name='uyemodel',
            name='veli_adi_soyadi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Veli Ad Soyad'),
        ),
        migrations.AddField(
            model_name='uyemodel',
            name='veli_telefon',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Veli Telefon'),
        ),
        migrations.AlterField(
            model_name='haftalikplanmodel',
            name='ders_baslangic_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='İlk Ders Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='aktif_mi',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktif mi'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='kimlikNo',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Kimlik No'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='onaylandi_mi',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Onay Durumu'),
        ),
    ]
