# Generated by Django 3.2.3 on 2023-02-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0041_auto_20230215_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uyemodel',
            old_name='kimlikNo',
            new_name='kimlik_no',
        ),
    ]
