# Generated by Django 3.2.3 on 2023-02-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0042_rename_kimlikno_uyemodel_kimlik_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlikmodel',
            name='iptal_eden',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etkinlikmodel',
            name='iptal_mi',
            field=models.BooleanField(default=False, verbose_name='İptal mi?'),
        ),
        migrations.AddField(
            model_name='etkinlikmodel',
            name='iptal_tarih_saat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İptal Tarih Saat'),
        ),
    ]
