# Generated by Django 3.2.3 on 2023-02-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0043_auto_20230215_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='parahareketimodel',
            name='paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paket_parahareketi_relations', to='calendarapp.uyepaketmodel'),
        ),
        migrations.AlterField(
            model_name='parahareketimodel',
            name='antrenor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='antrenor_parahareketi_relations', to='calendarapp.antrenormodel'),
        ),
        migrations.AlterField(
            model_name='parahareketimodel',
            name='uye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uye_parahareketi_relations', to='calendarapp.uyemodel'),
        ),
    ]
