# Generated by Django 3.2.3 on 2023-02-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0045_auto_20230220_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parahareketimodel',
            name='antrenor',
        ),
        migrations.RemoveField(
            model_name='parahareketimodel',
            name='paket',
        ),
        migrations.AlterField(
            model_name='parahareketimodel',
            name='hareket_turu',
            field=models.CharField(choices=[('Borc', 'Borç'), ('Alacak', 'Alacak')], default='Borç', max_length=20),
        ),
        migrations.AlterField(
            model_name='parahareketimodel',
            name='odeme_turu',
            field=models.CharField(choices=[('Aidat', 'Aidat'), ('Paket', 'Paket'), ('TekDers', 'Tek Ders'), ('FarkUcreti', 'Fark Ücreti'), ('Diger', 'Diğer')], default='Diğer', max_length=20),
        ),
        migrations.AlterField(
            model_name='parahareketimodel',
            name='uye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uye_parahareketi_relations', to='calendarapp.uyemodel'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='adres',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adres'),
        ),
        migrations.CreateModel(
            name='MuhasebeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yil', models.SmallIntegerField(verbose_name='Yıl')),
                ('ay', models.SmallIntegerField(verbose_name='Ay')),
                ('alacak', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=20, null=True, verbose_name='Alacak')),
                ('borc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=20, null=True, verbose_name='Borç')),
                ('uye', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uye_muhasebe_relations', to='calendarapp.uyemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
