# Generated by Django 3.2.13 on 2023-02-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0046_auto_20230222_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parahareketimodel',
            name='hareket_turu',
            field=models.CharField(choices=[('Borc', 'Borç'), ('Odeme', 'Ödeme')], default='Borç', max_length=20),
        ),
        migrations.AlterField(
            model_name='parahareketimodel',
            name='odeme_turu',
            field=models.CharField(choices=[('Aidat', 'Aidat'), ('Paket', 'Paket'), ('TekDers', 'Tek Ders'), ('FarkUcreti', 'Fark Ücreti'), ('Diger', 'Diğer')], default='Diğer', max_length=20, verbose_name='Türü'),
        ),
    ]
