# Generated by Django 3.2.13 on 2023-02-24 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0047_auto_20230224_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muhasebemodel',
            old_name='alacak',
            new_name='odeme',
        ),
    ]
