# Generated by Django 3.2.3 on 2023-03-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0048_rename_alacak_muhasebemodel_odeme'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcretTarifesiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adi', models.CharField(max_length=50, verbose_name='Adı')),
                ('seviye', models.CharField(choices=[('Kirmizi', 'Kırmızı'), ('Turuncu', 'Turuncu'), ('Sari', 'Sarı'), ('Yesil', 'Yeşil'), ('Yetiskin', 'Yetişkin'), ('TenisOkulu', 'Tenis Okulu')], max_length=20)),
                ('abonelik_tipi', models.CharField(choices=[('Uyelik', 'Üyelik'), ('Paket', 'Paket')], max_length=20)),
                ('kisi_sayisi', models.SmallIntegerField(verbose_name='Kişi Sayısı')),
                ('kisi_basi_ucret', models.SmallIntegerField(verbose_name='Kişi Başı Ücret')),
                ('ders_sayisi', models.SmallIntegerField(blank=True, null=True, verbose_name='Ders Sayısı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='parahareketimodel',
            name='uye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uye_parahareketi_relations', to='calendarapp.uyemodel', verbose_name='Üye'),
        ),
    ]
