# Generated by Django 3.2.3 on 2023-03-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0049_auto_20230301_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uyepaketmodel',
            name='toplam_fiyati',
        ),
        migrations.AddField(
            model_name='uyepaketmodel',
            name='ucret_tarifesi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.ucrettarifesimodel', verbose_name='Paket'),
            preserve_default=False,
        ),
    ]
