# Generated by Django 3.2.3 on 2023-03-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0050_auto_20230301_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parahareketimodel',
            old_name='odeme_turu',
            new_name='ucret_turu',
        ),
    ]
