# Generated by Django 3.2.3 on 2023-03-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0051_rename_odeme_turu_parahareketimodel_ucret_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='parahareketimodel',
            name='paket_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Paket Id'),
        ),
    ]
