# Generated by Django 3.2.13 on 2023-03-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0052_parahareketimodel_paket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parahareketimodel',
            name='paket_id',
        ),
        migrations.AddField(
            model_name='parahareketimodel',
            name='abonelik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonelik_parahareketi_relations', to='calendarapp.haftalikplanmodel'),
        ),
        migrations.AddField(
            model_name='parahareketimodel',
            name='paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paket_parahareketi_relations', to='calendarapp.uyepaketmodel'),
        ),
    ]
