# Generated by Django 3.2.13 on 2023-03-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0053_auto_20230302_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyemodel',
            name='profil_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='program_tercihi',
            field=models.CharField(blank=True, choices=[('Özel Ders', 'Özel Ders'), ('Grup', 'Grup'), ('Hobi', 'Hobi'), ('Altyapı', 'Altyapı')], max_length=100, null=True, verbose_name='Program Tercihi'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='tenis_gecmisi_var_mi',
            field=models.CharField(blank=True, choices=[('Var', 'Var'), ('Yok', 'Yok'), ('Az', 'Az')], max_length=10, null=True, verbose_name='Tenis Eğitim Geçmişi'),
        ),
        migrations.AlterField(
            model_name='uyemodel',
            name='uye_tipi',
            field=models.SmallIntegerField(choices=[('Yetişkin', 1), ('Sporcu', 2)], default=1, verbose_name='Üye Tipi'),
        ),
    ]
