# Generated by Django 4.1.7 on 2023-03-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0055_antrenormodel_ucret_katsayisi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telafidersmodel',
            options={'ordering': ['id'], 'verbose_name': 'Telafi Ders', 'verbose_name_plural': 'Telafi Ders'},
        ),
        migrations.AlterField(
            model_name='ucrettarifesimodel',
            name='abonelik_tipi',
            field=models.CharField(choices=[('Aidat', 'Aidat'), ('Paket', 'Paket'), ('Demo', 'Demo'), ('TekDers', 'Tek Ders')], max_length=20),
        ),
    ]
