# Generated by Django 4.1.7 on 2023-03-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0057_rename_top_rengi_etkinlikmodel_seviye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyepaketmodel',
            name='etkinlik_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Etkinlik ID'),
        ),
        migrations.AlterField(
            model_name='antrenormodel',
            name='renk',
            field=models.CharField(choices=[('red', 'Kırmızı'), ('orange', 'Turuncu'), ('yellow', 'Sarı'), ('gray', 'Gri'), ('pink', 'Pembe'), ('blue', 'Mavi'), ('green', 'Yeşil'), ('purple', 'Mor')], default='gray', max_length=20, verbose_name='Renk'),
        ),
    ]
